--- #YAML:1.0
name:               Bot-NotSoBasicBot
version:            0.02
abstract:           Builts on Bot::BasicBot, adding a little extra functionality for convenience.
author:
    - Michael Roberts <michael@vivtek.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bot::BasicBot:    0
    Config::Auto:     0
    Data::Dumper:     0
    Event::Schedule:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
